version: '3'

networks: 
    pubsub-net:
        driver: bridge

services:
    mosquitto1:
        image: eclipse-mosquitto
        container_name: mqtt-bridge
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto:/mosquitto/
        networks: 
            - pubsub-net